{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tpl.fullname" . }}
  labels:
    {{- include "tpl.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tpl.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end }}
