### Staging specific
replicaCount: 3

resources:
  limits:
    cpu: 1
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

strategy:
  # RollingUpdate strategy replaces old pods with new ones gradually,
  # without incurring downtime.
  type: RollingUpdate
  rollingUpdate:
    # maxUnavailable is the maximum number of pods that can be
    # unavailable during the update process.
    maxUnavailable: 30%
    # maxSurge is the maximum number of pods that can be
    # created over the desired number of pods
    maxSurge: 10%

podDisruptionBudget:
  enabled: false
  minAvailable: 50%
  # maxUnavailable: 1
