# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.okd4.teh-1.snappcloud.io/m-yosefpor/httpmon
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPort: 4000
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

################################## Best Practices
##################################

sysctls: []
  # # defaults to 128 in the kernel; Redis and ElasticSearch are examples of applications that would benefit from higher values.
  # # This value can be increased up to 65535 in SnappCloud.
  # - name: "net.core.somaxconn"
  #   value: "128"
  # # defaults to 32768 in the kernel. Can be increased to 60999 in SnappCloud.
  # - name: "net.ipv4.ip_local_port_range"
  #   value: "VALUE_HERE"

livenessProbe:
  httpGet:
    path: /healthz
    # port: 8080
    # httpHeaders:
    # - name: Custom-Header
    #   value: Awesome
  initialDelaySeconds: 3
  periodSeconds: 3
  failureThreshold: 3
  successThreshold: 1

readinessProbe: {}

startupProbe: {}
  # httpGet:
  #   path: /healthz
  #   port: liveness-port
  # failureThreshold: 30
  # periodSeconds: 10



### Production specific
replicaCount: 5

resources:
  limits:
    cpu: 3
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

strategy:
  # RollingUpdate strategy replaces old pods with new ones gradually,
  # without incurring downtime.
  type: RollingUpdate
  rollingUpdate:
    # maxUnavailable is the maximum number of pods that can be
    # unavailable during the update process.
    maxUnavailable: 0
    # maxSurge is the maximum number of pods that can be
    # created over the desired number of pods
    maxSurge: 10%

podDisruptionBudget:
  enabled: true
  minAvailable: 50%
  # maxUnavailable: 1


####################### Rarely shoud be changed
#######################
podAnnotations: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
